### ISSUE TITLE
Can't find web3.min.js

### ISSUE THREAD

**Issue by bobthegrownup** [shawntabrizi/ETH-Balance#1]
After downloading web3.js-1.0, I cannot find web3.min.js. Is there another option or somewhere else to download it?

**Comment by shawntabrizi** [comment]
@bobthegrownup This repository provides the web3.min.js file needed to get the project to work. If you are asking about some newer version of the file, you should look at the Web3.js repository.

Not quite sure how to help you...

**Comment by bobthegrownup** [comment]
Yes! smh sorry I thought I already had downloaded it. thanks for the quick reply :)
