### ISSUE TITLE
how send  web3.eth.getBalance value to var account1value?

### ISSUE THREAD

**Issue by tytom2003** [shawntabrizi/ETH-Balance#2]
if i want var account1value can get web3.eth.getBalance. How to do?
var account1value = web3.eth.getBalance('0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1');
it will show promise{<pending>}. 
if i must use the way to get.  How to do?
Thank you very much.

**Comment by shawntabrizi** [comment]
You need to resolve the promise.

Just adding `await` should work.

```
 var account1value = await web3.eth.getBalance('0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1');
```

Should work.

Learn more: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
